import {defineArrayMember, defineField, defineType} from 'sanity'

const navigationField = (name: string, title: string) =>
  defineField({
    name,
    title,
    type: 'array',
    of: [defineArrayMember({type: 'cta'})],
  })

export const siteSettings = defineType({
  name: 'siteSettings',
  title: 'Site settings',
  type: 'document',
  groups: [
    {name: 'identity', title: 'Identity'},
    {name: 'contact', title: 'Contact'},
    {name: 'navigation', title: 'Navigation'},
    {name: 'accessibility', title: 'Accessibility labels'},
    {name: 'seo', title: 'SEO'},
  ],
  fields: [
    defineField({
      name: 'siteName',
      title: 'Site name',
      type: 'string',
      initialValue: 'Estudio de Danza Carmen',
      validation: (rule) => rule.required(),
      group: 'identity',
    }),
    defineField({
      name: 'brandLabel',
      title: 'Visible brand label',
      type: 'string',
      initialValue: 'Danza Carmen',
      validation: (rule) => rule.required(),
      group: 'identity',
    }),
    defineField({
      name: 'topbarMessage',
      title: 'Top bar message',
      type: 'string',
      initialValue: 'Bienvenidos a nuestra academia de danza',
      group: 'identity',
    }),
    defineField({
      name: 'legalBusinessName',
      title: 'Legal business name',
      type: 'string',
      group: 'identity',
    }),
    defineField({
      name: 'address',
      title: 'Public address',
      type: 'text',
      rows: 3,
      initialValue: 'Calle Casillas de Prats, 10\n18002 Granada',
      validation: (rule) => rule.required(),
      group: 'contact',
    }),
    defineField({
      name: 'phone',
      title: 'Public phone',
      type: 'string',
      group: 'contact',
    }),
    defineField({
      name: 'phoneLabel',
      title: 'Visible phone label',
      type: 'string',
      description: 'Shown in the top bar. Use this while the real phone number is pending.',
      initialValue: 'Teléfono pendiente',
      group: 'contact',
    }),
    defineField({
      name: 'email',
      title: 'Public email',
      type: 'string',
      validation: (rule) => rule.email(),
      group: 'contact',
    }),
    defineField({
      name: 'generalHours',
      title: 'General hours',
      type: 'text',
      rows: 3,
      group: 'contact',
    }),
    defineField({
      name: 'footerNote',
      title: 'Footer note',
      type: 'text',
      rows: 2,
      initialValue: 'Contacto y horarios de atención pendientes de confirmación.',
      group: 'contact',
    }),
    navigationField('headerNavigation', 'Header navigation'),
    defineField({
      name: 'primaryNavigation',
      title: 'Primary navigation legacy fallback',
      type: 'array',
      of: [defineArrayMember({type: 'cta'})],
      validation: (rule) => rule.required().min(1),
      group: 'navigation',
    }),
    defineField({
      name: 'footerPrimaryTitle',
      title: 'Footer primary group title',
      type: 'string',
      initialValue: 'Principal',
      group: 'navigation',
    }),
    navigationField('footerPrimaryNavigation', 'Footer primary navigation'),
    defineField({
      name: 'footerSecondaryTitle',
      title: 'Footer secondary group title',
      type: 'string',
      initialValue: 'También en la escuela',
      group: 'navigation',
    }),
    navigationField('footerSecondaryNavigation', 'Footer secondary navigation'),
    defineField({
      name: 'footerLegalTitle',
      title: 'Footer legal group title',
      type: 'string',
      initialValue: 'Legal',
      group: 'navigation',
    }),
    navigationField('footerLegalNavigation', 'Footer legal navigation'),
    defineField({
      name: 'footerNavigation',
      title: 'Footer navigation legacy fallback',
      type: 'array',
      of: [defineArrayMember({type: 'cta'})],
      group: 'navigation',
    }),
    defineField({
      name: 'mainNavigationLabel',
      title: 'Main navigation aria label',
      type: 'string',
      initialValue: 'Navegación principal',
      group: 'accessibility',
    }),
    defineField({
      name: 'mobileNavigationLabel',
      title: 'Mobile navigation aria label',
      type: 'string',
      initialValue: 'Navegación principal',
      group: 'accessibility',
    }),
    defineField({
      name: 'footerNavigationLabel',
      title: 'Footer navigation aria label',
      type: 'string',
      initialValue: 'Navegación de pie de página',
      group: 'accessibility',
    }),
    defineField({
      name: 'searchLabel',
      title: 'Search link aria label',
      type: 'string',
      initialValue: 'Buscar clases',
      group: 'accessibility',
    }),
    defineField({
      name: 'menuLabel',
      title: 'Mobile menu label',
      type: 'string',
      initialValue: 'Menú',
      group: 'accessibility',
    }),
    defineField({name: 'seoDefaults', title: 'SEO defaults', type: 'seo', group: 'seo'}),
  ],
})
